name: Python Test Helper

on:
    workflow_call:
        inputs:
            python-version:
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ inputs.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ inputs.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade