# main.yaml
name: Main Workflow
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    call-helper:
        uses: ./.github/workflows/helper.yaml
        with:
            python-version: '3.12'